### ISSUE TITLE
Only DateTime ?

### ISSUE THREAD

**Issue by fxprunayre** [ISO-TC211/XML#117]
Is there any reason to only have DateTime support for dates. Eg. https://github.com/ISO-TC211/XML/blob/master/standards.iso.org/19115/-3/cit/1.0/citation.xsd#L85, https://github.com/ISO-TC211/XML/blob/master/standards.iso.org/19115/-3/cit/1.0/citation.xsd#L201

Should we use Date_PropertyType which allows year, yearmonth, date and datetime (like in ISO19139)
https://github.com/ISO-TC211/XML/blob/master/standards.iso.org/19115/-3/gco/1.0/baseTypes2014.xsd#L249
?

**Comment by fxprunayre** [comment]
Any comments on this ?

**Comment by PeterParslow** [comment]
ISO 19115-1:2014 gives DateTime as the data type for CI_Citation.editionDate, and for CI_Date.date (CI_Date is the data type for CI_Citation.date & other things).

But it then explicitly says (B.2.2) 'Character encoding of a DateTime shall follow ISO 8601. This class is documented in full in ISO/TS 19103. 

NOTE 2: Although the DateTime definition allows for more precise temporal statements, the less precise values can also be used. ...

NOTE 3 DateTime inherits both from Date and Time, which means that:
— a DateTime property can be instantiated either as a Date or as a DateTime;"

Therefore we should not restrict any occurrence of ISO 19115/19103 DateTime to only contain xs:dateTime.

I think the fault lies at https://github.com/ISO-TC211/XML/blob/master/standards.iso.org/19115/-3/gco/1.0/baseTypes2014.xsd line 236.It should define DateTime as a union (choice) of gco:Date_Type and xs:dateTime. 

I don't see that gco:Date_PropertyType should allow dateTime. That's not what 19115 says.

Sorry for not spotting this earlier.

**Comment by fxprunayre** [comment]
What would be the best to solve that ?

In ISO19115-1:2014, we have
![image](https://cloud.githubusercontent.com/assets/1701393/9436125/678c4dae-4a4d-11e5-8003-56908e7aa5bd.png)

And
![image](https://cloud.githubusercontent.com/assets/1701393/9436147/852dbaa0-4a4d-11e5-9333-0ac044fe539a.png)



Option1: Add xs:date xs:gYearMonth xs:gYear to DateTime 

```
<xs:element name="DateTime" type="xs:dateTime"/>
```
replaced by
```
<xs:element name="DateTime">
    <xs:simpleType>
      <xs:union memberTypes="xs:dateTime xs:date xs:gYearMonth xs:gYear"/>
    </xs:simpleType>
</xs:element>
```

Option2: Use Date_PropertyType (similar to ISO19139 implementation)

In https://github.com/ISO-TC211/XML/blob/master/standards.iso.org/19115/-3/cit/1.0/citation.xsd#L197
```
  <complexType name="CI_Date_Type">
    <complexContent>
      <extension base="mcc:Abstract_TypedDate_Type">
        <sequence>
          <element name="date" type="gco:DateTime_PropertyType">

```
replaced by
```
  <complexType name="CI_Date_Type">
    <complexContent>
      <extension base="mcc:Abstract_TypedDate_Type">
        <sequence>
          <element name="date" type="gco:Date_PropertyType">

```


Option 2 sounds more conform to "a DateTime property can be instantiated either as a Date or as a DateTime"
Option 1 will be too much flexible for field like plannedAvailableDateTime requiring both date & time.

Others questions:
* This will not cover the NOTE1 eg YY (century) or NOTE2 eg. YYYY-MM-DDThh. Should we also support those notations ?

**Comment by smrazgs** [comment]
I don't know why the data type for CI_Date was changed from Date to DateTime.  The more restrictive convention is better for interoperability--fewer options to deal with when clients are processing dates, but it does force making date values that are frequently pretty fuzzy (just a year...) look a lot more precise than they are. I'll broadcast the question to @DaveDanko  and see if he can enlighten us.  

Of the options you outline, I'd favor implementing CI_Date with the gco:Date_PropertyType as was done in 19139.

**Comment by tedhabermann** [comment]
I have been trying to remember the discussion during the revision of 19115-1 but can't. I think we made this change in order to make the dates more general, in other words, to include all options, i.e. times as well as dates, but that the xs:dateTime type that is assigned to gco:DateTime (in baseTypes2014.xsd) turned out to be more restrictive than we expected (see http://books.xmlschemata.org/relaxng/ch19-77049.html). In other words, this was an unintended side effect of our attempt to generalize. I agree that making this general enough to support all precisions is a good thing.

**Comment by DaveDanko** [comment]
that's my recollection as well. we wanted to add time as an option for datasets published every few minutes but to be flexible allowing all types of precision.

**Comment by smrazgs** [comment]
I've created a branch with Francois' Option 2 implemented. See pull request pull/#139

**Comment by kateroberts** [comment]
WRT Francois comment that Option 2 " ...will not cover the NOTE1 eg YY (century) or NOTE2 eg. YYYY-MM-DDThh. Should we also support those notations ?",
if there is a reasonably easy way to address these, I think it would be good to do so, partly because the 19115 doc says its allowable, and also because it makes 19115 flexible for the edge cases.

**Comment by ejbleijs** [comment]
ISO 19115-3 class CI_Date attribute date is based on ISO 8601
ISO 8601:2019 identifies [dateE][timeE] hence dateTime may be represented as date alone.

**Comment by ronaldtse** [comment]
@ejbleijs the current ISO 19115-3 refers to ISO 8601:2004, but since it is up for revision soon, this will be an opportunity to update it to support ISO 8601-1:2019 which contains `[dateE][timeE]` for better alignment.

**Comment by ejbleys** [comment]
Agreed

Evert Bleys
4 Tudor Place HUGHES ACT 2605
Australia
+61 (0)2 62811773
+61 (0)411 483 876
ejbleys@gmail.com
Skype ejbleijs@gmail.com
