### ISSUE TITLE
what is good location to reference for ISO XSD

### ISSUE THREAD

**Issue by mhogeweg** [ISO-TC211/XML#118]
hi, within Geoportal Server we used to reference the ISO schemas hosted at IGN France. however, recently these schemas have disappeared (as reported by a user in [this issue](https://github.com/Esri/geoportal-server/issues/180) on the Geoportal Server repo). is there a formal permanent location for ISO schemas we can use?

**Comment by jacimize** [comment]
http://www.ngdc.noaa.gov/metadata/published/xsd/schema.xsd

http://www.ngdc.noaa.gov/metadata/published/xsd/

**Comment by mhogeweg** [comment]
thanks! we'll use these instead. however, would be nice if ISO provided a permanent location themselves.

**Comment by fxprunayre** [comment]
It looks like at some point this http://standards.iso.org/ will be the location to use ?

**Comment by DaveDanko** [comment]
yes - http://standards.iso.org/iso/

**Comment by mhogeweg** [comment]
even better.

**Comment by smrazgs** [comment]
19119 metadata is implemented as part of ISO19115-3-- see the srv namespace package.
I think we can close this one.
