### ISSUE TITLE
fcc/abstract.xsd has wrong relative path to gco.xsd

### ISSUE THREAD

**Issue by alwalsh** [ISO-TC211/XML#136]
Hi 19115-3 Team,

Great work, hi to FXP and Ted.

I am starting to look at 19115-3 standard in connection with work in Australia on new ANZLIC metadata
guidelines document for 19115-1:2014. I am constructing XML samples off the schema using
XML spy

The 19115.zip schema I downloaded from http://standards.iso.org/iso/19115/ has a path error in
file fcc/abstract.xsd. (same issue is in 19115.zip schema in github) Fix was as follows:

	
	

	
	<import namespace="http://standards.iso.org/iso/19115/-3/gco/1.0" schemaLocation="../../../19115/-3/gco/1.0/gco.xsd"/>

With this change the schema was fixed and I was able to validate XML instance e.g
https://github.com/ISO-TC211/XML/blob/master/standards.iso.org/19115/-3/mds/1.0/AppendixD.2VectorSmartMapExample.xml

against schema on web or local schema on disc.

If someone could fix would appreciate.

Andrew Walsh
RAN-Metoc

**Comment by smrazgs** [comment]
correction made.
