### ISSUE TITLE
xml sample mds.xml has typo in xsi:schemaLocation namespace

### ISSUE THREAD

**Issue by alwalsh** [ISO-TC211/XML#137]
Hi,

https://github.com/ISO-TC211/XML/blob/master/standards.iso.org/19115/-3/mds/1.0/mds.xml

has 

xsi:schemaLocation="http://standards.iso.org/iso/19115/-3/mdb/1.0 mds.xsd

should be 

xsi:schemaLocation="http://standards.iso.org/iso/19115/-3/mds/1.0 mds.xsd

i.e 'mdb' should 'mds'

XML sample validates OK after this change.

Andrew Walsh
RAN-Metoc

PS: same issue on github repo and in 19115.zip archive, so update both

**Comment by smrazgs** [comment]
fixed. close issue
