### ISSUE TITLE
ISO19110 is valueType on Feature Attribute mandatory

### ISSUE THREAD

**Issue by smrazgs** [ISO-TC211/XML#153]
The data dictionary and 19110(E) text both have valueType ('data type') in 6.2.6 in the original text as a mandatory property of FEature attribute, but the UML and XML implementation both have this as an optional property (0..1).
Either the text or the UML and XML need to be updated to make the optionality consistent.

**Comment by jacimize** [comment]
In these cases for this particular standard, is the authoritative fall back
to reference the text?

Cheers,
Jaci

On Mon, Dec 28, 2015 at 11:58 AM, Stephen Richard <notifications@github.com>
wrote:

> The data dictionary and 19110(E) text both have valueType ('data type') in
> 6.2.6 in the original text as a mandatory property of FEature attribute,
> but the UML and XML implementation both have this as an optional property
> (0..1).
> Either the text or the UML and XML need to be updated to make the
> optionality consistent.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ISO-TC211/XML/issues/153>.
>



-- 
Jacqueline Mize
Metadata Specialist
Riverside Technology, Inc.
NOAA National Centers for Environmental Information
1021 Balch BLVD, Suite 1002
Stennis Space Center, MS 39529
email: Jacqueline.Mize@noaa.gov
ph: 228.688.2174

**Comment by PeterParslow** [comment]
That would be the case if the amended ISO 19110 were a published standard. After many delays over the past few years, TC211 has again extended the project's deadline - . The comments (against the DIS) that are being worked on include a couple of recommendations to change multiplicity. 

Unfortunately, I can't see any documents in the livelink ISO19110rev folder (within WG7), so I can't see the text that 'smrzgs' (!) commented on.

One explanation could be that the presence of FeatureAttribute.valueType is conditional. This is the case in the currently published version of 19110, which has FC_FeatureAttribute.valueType as Conditional 'Mandatory if feature attribute listedValue is empty'. Amendment 1 changed the condition to 'Mandatory for local feature attribute'. 

If this isn't clear in the new text, then I would ask the current working group convenor (in the apparent absence of a project leader) what the intention is. That's Antony Cooper.

**Comment by jetgeo** [comment]
The case with valueType is that it exists two places in the conceptual model: on FC_FeatureAttribute and on FC_BoundFeatureAttribute (for global attributes). There are constraints on both classes, making valueType mandatory:
- FC_FeatureAttribute has constraint "valueType is mandatory for local feature attribute"
- FC_BoundFeatureAttribute has constraint "valueType is mandatory if the value type of the feature attribute is not defined globally".
These constraints are identical in the conceptual UML model and in the dictionary in Annex B of the DIS document.
I guess this has to be handled through Schematron in XML?

**Comment by smrazgs** [comment]
I see. The constraint in the UML model handles the cardinality. Closing issue.
the current draft attempting to handle requirements and conformance classes using the pattern from ISO19115-3 is in the 19110 drop box
