### ISSUE TITLE
ISO19110 what properties are mandatory

### ISSUE THREAD

**Issue by smrazgs** [ISO-TC211/XML#154]
The data dictionary and 19110(E) text both have valueType ('data type' in 6.2.6) and 'definition' in the original text as a mandatory property of Feature attribute, but the UML and XML implementation both have this as an optional property (0..1).

 the text makes definitions mandatory, but in the UML and XML they are optional. (featureType, ListedValue, PropertyType)

Either the text or the UML and XML need to be updated to make the optionality consistent.

**Comment by jetgeo** [comment]
This is handled by constraints in the conceptual model (Ref https://github.com/ISO-TC211/XML/issues/153);
FC_FeatureAttribute.valueType is mandatory for local feature attributes, and FC_BoundFeatureAttribute is mandatory if valueType is not defined on the related FC_FeatureAttribute. In other words, all feature attributes shall have value type, either directly or through a releated instance. 

FC_FeatureAttribute.defintion and FC_FeatureType.definition is also mandatory by constraints. The definition shall either be given directly or through a definition source. 

I guess this has to be handled by Schematron in XML?

**Comment by smrazgs** [comment]
That make sense. The way its set up in the 1226 doc is the conceptual requirement is that there's a definition, and the test for conceptual conformance is to verify that there is such a constraint (e.g. definition is either inline or is provided by reference).  This has to be implemented via schematron; There is not automated way to transform the UML constraints statements to schematron, so reliance on those does present an issue for the rule-based schema for validation.
