### ISSUE TITLE
LE_Processing Changes

### ISSUE THREAD

**Issue by tedhabermann** [ISO-TC211/XML#167]
add otherProperty, otherPropertyType
add LE_ProcessParameter

**Comment by alwalsh** [comment]
Hi Ted,

Will these recent changes raised for revision of ISO 19115-2 flow through to to ISO 19115-1 and if so when, roughly, do you think ISO 19115-1 would be updated on the official schema?

Kind Regards,

Andrew Walsh

**Comment by alwalsh** [comment]
Hi Ted,

Apologies should rephrase this question, I got mixed up with standards vs. XML implementation. I should say:

"Will these recent changes raised for revision of ISO 19115-2 flow through to to ISO 19115-3 and if so when, roughly, do you think ISO 19115-3 would be updated on the official schema?"

Hi Kate,

Looks like you understood my question anyway -:)

Andrew

**Comment by tedhabermann** [comment]
Done
