### ISSUE TITLE
LE_ProcessParameter: suggest defining locally

### ISSUE THREAD

**Issue by smrgeoinfo** [ISO-TC211/XML#169]
Currently LE_ProcessParameter is a subtype of SV_Parameter, which introduces a dependency between Extended Lineage Information and ServiceInformation.   If you look for 'parameter' in the full TC211 UML model, there are at least 15 'parameter' classes defined in 10 standards, so people have felt free to create local parameter classes specific to particular models.
I'd suggest rather than extending SV_Parameter (admittedly a nice generic parameter type definition) and having to deal with the dependency, define the LE_ProcessParameter class in the Extended Lineage Information package (would have to define a local 'parameter direction' enumeration as well).  I don't see any particular benefit in reusing the definition in ServiceInformation.

**Comment by tedhabermann** [comment]
The proposal is currently is to add the properties that are currently in SV_Parameter to LE_ProcessingPrameter. The result is LE_ProcessingParameter that includes:
name : MemberName (gives name/type of parameter)
direction: codelist (in, out, in/out)
description: CharacterString [0..1]
optionality: Boolean
repeatability: Boolean
valueType: RecordType [0..1]
value: Record [0..*]
