### ISSUE TITLE
 Discrepancies between schema, standard and UML

### ISSUE THREAD

**Issue by jacimize** [ISO-TC211/XML#175]
If any discrepancies are found between the schema and the standards and UML,  as a best practice what should the community refer to as the authoritative resource?

**Comment by tedhabermann** [comment]
Jaci,

19115-1 states: If a discrepancy exists between the UML models provided in Clause 6 and Annex B, the UML models shall be considered authoritative. 19115-3 doesn’t say…

Curious – did you find A discrepancy?

Ted

==== Ted Habermann ========================
Director of Earth Science, The HDF Group
Voice: (217) 531-4202
Email: thabermann@hdfgroup.org
==== HDF: Software That Powers Science ====

**Comment by jacimize** [comment]
No no discrepancies were found but this question was brought up  while trying to define best practices.  I had remembered that it was the UML  but wanted to confirm that that was still the case.
