### ISSUE TITLE
Wiki section regarding legacy codelists should be updated

### ISSUE THREAD

**Issue by heidivanparys** [ISO-TC211/XML#180]
1. The text says "The most recent versions of these codelists have been moved to http://standards.iso.org/iso/19139/resources/codelist" but this URL gives a 404 exception. Should it be http://standards.iso.org/iso/19139/resources/ instead?
![image](https://user-images.githubusercontent.com/11427611/33308945-b8adce3c-d41c-11e7-9c26-7c163ff86884.png)
2. Layout: The layout for the section regarding legacy codelists is probably not as intended, it is supposed to be a table but it currently displayed as following:
![image](https://user-images.githubusercontent.com/11427611/33308825-5b177c14-d41c-11e7-87e1-94a44fad0ca1.png)

**Comment by tedhabermann** [comment]
Thanks for pointing this out. I fixed it...
