### ISSUE TITLE
Definitive 19139/19115 xml schemas? (not -2, -1, -3)

### ISSUE THREAD

**Issue by shane-axiom** [ISO-TC211/XML#192]
Hi, are there any plans to add the original 19139/19115 schemas to this repository/standards.iso.org?

I assumed that the versions here would be authoritative:

http://www.isotc211.org/2005/

but they suffer from a GML namespace problem (the GML 3.1.1 namespace `http://www.opengis.net/gml` is used, but the namespace should actually be `http://www.isotc211.org/2005/gml` referencing the embedded GML 3.2.0 version). This causes documents using these schemas to fail validation when namespace based validation is used. The problem is discussed here:

https://inspire-forum.jrc.ec.europa.eu/pg/forum/topic/7339/20070417-version-19139-schemas-for-service-metadata/#Item_1617

A "mopping up" revision of the schemas hosted at http://schemas.opengis.net/iso/19139/20070417/ resolves this issue by using the `http://www.opengis.net/gml/3.2` namespace (which points to the since-released GML 3.2.1), and seems to be widely used (e.g. by the [ogc-schemas](https://github.com/highsource/ogc-schemas/blob/master/iso19139/20070417/pom.xml#L33-L50) JAXB bindings project).

Many consumers of these documents seem to depend on predictable namespaces, so we want to be able to use an official but valid set of schemas in our documents.

Should http://schemas.opengis.net/iso/19139/20070417/ be regarded as the definitive set of schemas? If not, can a fixed set of 19139/19115 schemas be added to standards.iso.org?

@tedhabermann @dr-shorthair

**Comment by shane-axiom** [comment]
> If not, can a fixed set of 19139/19115 schemas be added to standards.iso.org?

BTW I'm happy to set up a pull request if they should be added here.

**Comment by shane-axiom** [comment]
Another variant being used in `schemaLocation`s in the wild:

https://www.ngdc.noaa.gov/metadata/published/xsd/schema/

**Comment by shane-axiom** [comment]
Just found this noted at http://schemas.opengis.net/iso/19139/20070417/ReadMe.txt:

http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/

So I guess that's the offical `schemaLocation` that should be used? e.g. `http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmd/gmd.xsd`

**Comment by smrgeoinfo** [comment]
Yes, the  xml schema at http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmd/gmd.xsd is used as the authoritative implementation of the xml namespace http://www.isotc211.org/2005/gmd.  The Namespace URI is an identifier for the namespace, not a location for the xml schema  implementing the namespace.

**Comment by shane-axiom** [comment]
@smrgeoinfo Thanks for the verification, that's helpful. You're of course correct, I misspoke above and conflated namespace URIs and schemaLocations, meant to say that some consumers depend on a predictable schemaLocation/set of schemas. I think some validation issues I've been encountering have to do with a mix of the older http://www.isotc211.org/2005/ schemas and newer schemas.opengis.net/iso/19139/20070417/ schemas being used in the pipeline, but now that we can focus on using schemas from http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/ the situation will be much clearer. Thanks again.
