### ISSUE TITLE
Incorrect rule in ISO 19115-3 mrc.sch schematron

### ISSUE THREAD

**Issue by asedgmen** [ISO-TC211/XML#212]
Schematron rule in https://schemas.isotc211.org/schemas/19115/-3/mrc/1.0/mrc.sch for the MD_SampleDimension constraint is incorrect.  The ISO 19115-1 specification states {if count(maxValue + minValue + meanValue) > 0 then units is mandatory}.  The mrc.sch schematron rule for this constraint incorrectly asserts {count(maxValue + minValue + meanValue) > 0 }, i.e. at least one of maxValue, minValue and meanValue must exist.

**Comment by ejbleys** [comment]
Your version has been accepted (and transformed into Version for ISO 19115-1 & -2 V1.3
