### ISSUE TITLE
https://www.isotc211.org/2005/gfc/gfc.xsd imports non-existent xsds

### ISSUE THREAD

**Issue by shane-axiom** [ISO-TC211/XML#214]
https://www.isotc211.org/2005/gfc/gfc.xsd still tries to import XSDs from http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas, which no longer exists.

```
<xs:import namespace="http://www.isotc211.org/2005/gmd" schemaLocation="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmd/citation.xsd"/>
<xs:import namespace="http://www.isotc211.org/2005/gco" schemaLocation="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gco/gco.xsd"/>
<xs:import namespace="http://www.isotc211.org/2005/gmx" schemaLocation="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmx/gmx.xsd"/>
```

These should be updated to their schemas.isotc211.org equivalents

```
<xs:import namespace="http://www.isotc211.org/2005/gmd" schemaLocation="https://schemas.isotc211.org/schemas/19139/-/gmd/1.0/citation.xsd"/>
<xs:import namespace="http://www.isotc211.org/2005/gco" schemaLocation="https://schemas.isotc211.org/schemas/19139/-/gco/1.0/gco.xsd"/>
<xs:import namespace="http://www.isotc211.org/2005/gmx" schemaLocation="https://schemas.isotc211.org/schemas/19139/-/gmx/1.0/gmx.xsd"/>
```

Not sure if the maintainers of this repo have control over https://www.isotc211.org/2005/gfc/gfc.xsd, but I have no idea who else to ask.

**Comment by shane-axiom** [comment]
@tedhabermann Also, would it be possible to get gfc 0.1 (or is it 1.0) hosted on schemas.isotc211.org?

**Comment by ejbleys** [comment]
Yes,
I will put at https://schemas.isotc211.org/19110/-/gfc/1.0/gfc.xsd 
there is an  https://schemas.isotc211.org/19110/gfc/1.1/gfc.xsd and https://schemas.isotc211.org/19110/gfc/1.1/featureCatalogue.xsd 
Evert Bleys
4 Tudor Place HUGHES ACT 2605
Australia
+61 (0)2 62811773
+61 (0)411 483 876
ejbleys@gmail.com
Skype ejbleijs@gmail.com

**Comment by shane-axiom** [comment]
Thank you!

**Comment by ejbleys** [comment]
Sorry - 
Rash promise
I do not have a copy of 1.0
only the 1.1 in https://schemas.isotc211/19110/gfc/1.1/…
Cheers
e
Evert Bleys
4 Tudor Place HUGHES ACT 2605
Australia
+61 (0)2 62811773
+61 (0)411 483 876
ejbleys@gmail.com
Skype ejbleijs@gmail.com

**Comment by shane-axiom** [comment]
How about gfc 0.1 from https://www.isotc211.org/2005/gfc/gfc.xsd then? (Although, I'm about to submit a pull request to fix the namespace imports, so maybe wait until that's merged)

**Comment by ejbleys** [comment]
Can do
Evert Bleys
4 Tudor Place HUGHES ACT 2605
Australia
+61 (0)2 62811773
+61 (0)411 483 876
ejbleys@gmail.com
Skype ejbleijs@gmail.com

**Comment by ejbleys** [comment]
Is done in GitHub and should be automatically ported
https://schemas.isotc211/19110/-/gfc/1.0/gfc.xsd  seems to exist
It is an adjusted copy of  https://www.isotc211.org/2005/gfc/gfc.xsd <https://www.isotc211.org/2005/gfc/gfc.xsd>
	modified schema locations to point to https://schemas.isotc211.org/19139/-/~
  		gmd/1.0/citation.xsd
   		gco/1.0/gco.xsd
   		gmx/1.0/gmx.xsd
	    namespace URIs unchanged

Cheers
e
Evert Bleys
4 Tudor Place HUGHES ACT 2605
Australia
+61 (0)2 62811773
+61 (0)411 483 876
ejbleys@gmail.com
Skype ejbleijs@gmail.com

**Comment by shane-axiom** [comment]
Perfect, validation is working using `xsi:schemaLocation="http://www.isotc211.org/2005/gfc https://schemas.isotc211.org/19110/-/gfc/1.0/gfc.xsd"`. Thank you!
