### ISSUE TITLE
How to download ISO19115, ISO19136 and ISO19139 schema's in a ZIP to be stored locally

### ISSUE THREAD

**Issue by MartinePaepen** [ISO-TC211/XML#219]
For validation purposes, I have the schema's for ISO 19115 / ISO 19136 and ISO 19139 stored locally.
These were based on the schema's located at  <http://standards.iso.org/>.
Currently the schema's has been deprecated and don't validate any more because of the  unexisting http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/ 
 
Now it is recommended to use  https://schemas.isotc211.org<https://schemas.isotc211.org/> 

How can I download the ISO19115 / ISO19136 and ISO19139 schema's?
Could you provide me a ZIP with all the currently applicable schema's for validating my INSPIRE metadata files?

Thanks in advance
Martine

**Comment by ejbleys** [comment]
To obtain the most recently pulled schemas.
Got to: https://github.com/ISO-TC211/schemas
Change "<> Code" to "Download ZIP"
and a ZIPPED copy should arrive in your Downloads bucket
