### ISSUE TITLE
ISO 19115-2:2019 schemas - gmi 2.0

### ISSUE THREAD

**Issue by PeterParslow** [ISO-TC211/XML#225]
ISO 19115-2:2019 C.1 says 

The XML Schema for encoding this document can be found online at http://standards.iso.org/iso/19115/-2/gmi followed by the appropriate version number (2.0).

This should contain extensions to ISO 19115-3's mac, mrc, mri, msr, cit 

I can't find a gmi 2.0 either there are at the more likely URL / in here.

**Comment by ejbleys** [comment]
Those schemas have been retired and are not manageable by TC211
Use the schemas from https://schemas.ISO TC211.org/19115/…

Evert Bleys
4 Tudor Place
HUGHES ACT
Australia
Mob: 0411 483 876

**Comment by ejbleys** [comment]
GMI was retired and replaced within 19115-2 becoming MAC and should not appear in the 2019 version

Sorry:  traveling without access to schemas and tools
Cheers 
Evert
Evert Bleys
4 Tudor Place
HUGHES ACT
Australia
Mob: 0411 483 876

**Comment by ejbleys** [comment]
Correct
Replaced with namespace Mac

Evert Bleys
4 Tudor Place
HUGHES ACT
Australia
Mob: 0411 483 876

**Comment by PeterParslow** [comment]
My apologies; this was corrected in ISO 19115-2:2019/Amd 1:

Amended versions of the standard should now say

"The XML Schemas for encoding this document can be found online at
https://schemas.isotc211.org/schemas/19115/ followed by “-3” and the appropriate version number
(2.0)"

and https://schemas.isotc211.org/schemas/19115/-3/mac/2.0 for example does work.
