### ISSUE TITLE
Cannot clone this repo, redundant space in folder name?

### ISSUE THREAD

**Issue by heidivanparys** [ISO-TC211/XML#227]
I have issues with cloning this repository. The last attempt I made gave a clue though. I followed the instructions at https://stackoverflow.com/questions/21277806/fatal-early-eof-fatal-index-pack-failed and got the following error:

```
git clone --depth 1 https://github.com/ISO-TC211/XML.git
```

```
error: invalid path 'schemas.isotc211.org/19131/-/dps/2.2.1 /dps.xsd'
```

See also https://github.com/ISO-TC211/XML/tree/master/schemas.isotc211.org/19131/-/dps/2.2.1%20, there is an extra space in the folder name.

So the folder name is “2.2.1 " but should probably be “2.2.1”.

**Comment by ejbleys** [comment]
ThanksI’ll sort it outEEvert Bleys4 Tudor PlaceHUGHES ACTAustraliaMob: 0411 483 876On 4 Jan 2023, at 02:44, Heidi Vanparys ***@***.***> wrote:﻿
I have issues with cloning this repository. The last attempt I made gave a clue though. I followed the instructions at https://stackoverflow.com/questions/21277806/fatal-early-eof-fatal-index-pack-failed and got the following error:
git clone --depth 1 https://github.com/ISO-TC211/XML.git

error: invalid path 'schemas.isotc211.org/19131/-/dps/2.2.1 /dps.xsd'

See also https://github.com/ISO-TC211/XML/tree/master/schemas.isotc211.org/19131/-/dps/2.2.1%20, there is an extra space in the folder name.
So the folder name is “2.2.1 " but should probably be “2.2.1”.

**Comment by heidivanparys** [comment]
Great, thanks, it works now.
