### ISSUE TITLE
How-to be independent of XML Schema locations?

### ISSUE THREAD

**Issue by PeterParslow** [ISO-TC211/XML#230]
Would it be still relevant and useful to make this 2012 "XMG 0012" a public document?
I'm sure it was at some point(s) in the past - it was certainly cleared to be. It does not appear in the current ISO Documents system (at least, under XMG)
[XMG_0012.docx](https://github.com/ISO-TC211/XML/files/14539279/XMG_0012.docx)
[XMG_0012.pdf](https://github.com/ISO-TC211/XML/files/14539280/XMG_0012.pdf)

**Comment by PeterParslow** [comment]
Apologies, it is already public at https://www.iso.org/committee/54904.html
How to make that more easily discoverable? E.g.

- link from the XML resources page?
- link from the committee page to https://www.iso.org/committee/54904.html (currently it's only linked from the "red" page)

**Comment by ejbleys** [comment]
Still relevant, Thanks, will bring up at 2024-11-13 AG10 meeting
