### ISSUE TITLE
lineageImagery.xsd - softwareReference cardinality

### ISSUE THREAD

**Issue by tedhabermann** [ISO-TC211/XML#31]
This element has a default maxOccurs of 1. It needs to be maxOccurs = "unbounded". I suspect that this is an error in the harmonized model.

**Comment by smrazgs** [comment]
it is indeed 0..1 in the UML model (Harmonized model).  Since that's how it is in the HM, I think we have to leave it that way in the XML...  Is there an Issue tracker for 19115-2?

**Comment by smrazgs** [comment]
Yup, Its 0..1 in 19115-2 UML and in the XML implementation model for 19115-3.  The XML must be consistent with the UML, so I don't think we can change it in the implementation.... A topic for 19115-2 revision. I'll close this for now.
