### ISSUE TITLE
SensorTypeCode

### ISSUE THREAD

**Issue by tedhabermann** [ISO-TC211/XML#36]
NGDC, 2010-07-30, and 19115-3 all include SensorTypeCode but it is not used. Probably an error in the Harmonized Model.

**Comment by smrazgs** [comment]
The codelist element has no codelist values in the 19115-2 UML, and is not used as a data type for any XML property.  Should be removed from HM. I guess we need to leave it in the XML -- it shouldn't hurt anything.

**Comment by dr-shorthair** [comment]
I can't find any mention of it in the actual document. Since the document is normative it would be "legal" to remove the class from the UML. I guess it is cruft.

**Comment by PeterParslow** [comment]
I was about to say much the same: can’t see it in the text I have for 19115-2:2008, but I can’t actually find it in the UML either, or in the XSDs that I use (from Eden). So I’m not sure where you want to delete it from?
Peter
