### ISSUE TITLE
empty dateType

### ISSUE THREAD

**Issue by tedhabermann** [ISO-TC211/XML#37]
<gmd:date>
    <gmd:CI_Date>
        <gmd:date>
            <gco:Date>2777-07-07</gco:Date>
        </gmd:date>
        <gmd:dateType/>
    </gmd:CI_Date>
</gmd:date>
is transforming to
<cit:date>
    <cit:CI_Date>
        <cit:date>
            <gco:DateTime>2777-07-07T00:00:00</gco:DateTime>
        </cit:date>
    </cit:CI_Date>
</cit:date>
which is an error because cit:CI_Date must have a type.

**Comment by tedhabermann** [comment]
Not sure what to do with this one... DateType is required in 19115...

**Comment by fxprunayre** [comment]
:+1: if not valid in the input, no reason to have it valid in the output

**Comment by tedhabermann** [comment]
At this point I am going with not fixing items that are invalid in the source. Seems like a slippery slope to me...
