### ISSUE TITLE
XSL Transformation / map PixelOrientationCode center = centre

### ISSUE THREAD

**Issue by fxprunayre** [ISO-TC211/XML#64]
"centre" here https://github.com/ISO-TC211/XML/blob/master/standards.iso.org/19115/-3/msr/1.0/2014-12-25/spatialRepresentation.xsd#L273 should be "center" ?

![image](https://cloud.githubusercontent.com/assets/1701393/6061484/7a7aa3b8-ad48-11e4-9235-bec26238346e.png)

**Comment by PeterParslow** [comment]
François,
No – in common with other ISO standards, ISO 19115-1 uses British spelling – so ‘centre’ (specifically, see Figure 11 & B.3.24 of ISO 19115-1:2014)
Peter

**Comment by fxprunayre** [comment]
Yep sorry, was looking into the DIS.

So then, the XSL transformation  needs to take care of that mapping.

Thanks.

**Comment by PeterParslow** [comment]
I hadn’t spotted that it was the US spelling in 19115 & http://www.isotc211.org/2005/gmd/spatialRepresentation.xsd, so yes, it’s a transformation

Peter

**Comment by tedhabermann** [comment]
Fixed
