### ISSUE TITLE
reference to feature catalog from 19115-3 content.xsd

### ISSUE THREAD

**Issue by smrazgs** [ISO-TC211/XML#67]
Last(???) major issue-- the link to feature catalog in contentInformation is 
```
<extension base="mcc:Abstract_ContentInformation_Type">
        <sequence>
          <element maxOccurs="unbounded" name="featureCatalogue" 
type="fcc:Abstract_FeatureCatalogue_PropertyType">....
```
this imports the abstract featureCatalog namespace in the new 19110 implementation; should this be xs:any typed to avoid using our 'non-normative' 19110 implementation?

**Comment by smrazgs** [comment]
note the 19110 implementation at http://www.isotc211.org/2005/gfc/gfc.xsd.  It imports gmd, so using it with -3 will bring in all the older 19115 implementation as well... Also doesn't have the abstract class for decoupling.

**Comment by fxprunayre** [comment]
> note the 19110 implementation at http://www.isotc211.org/2005/gfc/gfc.xsd. It imports gmd,

This is now fixed no ?
https://github.com/ISO-TC211/XML/blob/master/standards.iso.org/19110/gfc/1.1/gfc.xsd

Any other pending items in this ticket ?

**Comment by smrazgs** [comment]
Decision was to link 19115-3 to the new implementation of 19110 (https://github.com/ISO-TC211/XML/blob/master/standards.iso.org/19110/gfc/1.1/gfc.xsd); this assumes that the 19110 WG will keep the implementation consistent with 19115-3. 

Close for now
