### ISSUE TITLE
Namespace URIs for 19139 gco and gmw

### ISSUE THREAD

**Issue by smrazgs** [ISO-TC211/XML#87]
Perhaps the revised gco and gmw namespace implementations should have new version numbers since the implementation is slightly different from the current gco and (gts, gss, gsr) that were put together in gmw.

**Comment by smrazgs** [comment]
We refactored the implementation of the base data types that originated in ISO19139 to include in ISO19115-3. This is in recognition of the fact that the implementations of the elements from ISO19103, ISO19107 and ISO19111 are all based on ISO19136 (GML). The gco package has no dependencies except XML schema and Xlink. The gmw package is a 'wrapper' for elements implemented in ISO19136.  
Anyway, these are currently still implemented with ISO 19139 namespace URIs:
http://standards.iso.org/19139/gco/1.0, 
http://standards.iso.org/19139/gmw/1.0

Since 19115-3 will supersede 19139, and because we are implementing an new version of these namespaces, I think it makes more sense to include them in the 19115-3 package, with URIs thus:
http://standards.iso.org/19115/-3/gco/1.0
http://standards.iso.org/19115/-3/gmw/1.0

**Comment by tedhabermann** [comment]
+1 will try to get to this this afternoon

**Comment by DaveDanko** [comment]
+1 good idea - this solves the issue I've been worried about since we started

**Comment by DaveDanko** [comment]
+1  this solves the issue I've been worried about since we started

**Comment by tedhabermann** [comment]
made these changes
