### ISSUE TITLE
mdt.xml contains ref to namespace with 2014-12-25

### ISSUE THREAD

**Issue by fxprunayre** [ISO-TC211/XML#92]
See https://github.com/ISO-TC211/XML/blob/master/standards.iso.org/19115/-3/mdt/1.0/mdt.xml#L3

Should probably not ?

**Comment by tedhabermann** [comment]
Arrrrrggggg! I thought I had all of these fixed... Will get to it this afternoon...

**Comment by fxprunayre** [comment]
Fixed in https://github.com/ISO-TC211/XML/commit/9344466c05f5777fa211470f72989eb773992d22#diff-03fa6e2b002e04a5f84f0732cc10b87a. Closing.
